/**
 * Lightweight utility to call Google Gemini API via REST
 */
export async function callGemini(prompt: string): Promise<string> {
  const API_KEY = process.env.GEMINI_API_KEY;
  const MODEL = "gemini-2.5-flash";
  const ENDPOINT = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${API_KEY}`;

  if (!API_KEY) {
    throw new Error("GEMINI_API_KEY is not configured in environment variables.");
  }

  const response = await fetch(ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            {
              text: prompt,
            },
          ],
        },
      ],
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error?.error?.message || "Gemini API request failed");
  }

  const data = await response.json();

  // Extract text from the response structure
  try {
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!generatedText) {
      throw new Error("No text generated by Gemini");
    }
    return generatedText;
  } catch (err) {
    console.error("Failed to parse Gemini response:", data);
    throw new Error("Unexpected response structure from Gemini API");
  }
}
